import { StyleSheet } from "react-native";
import { RFValue } from "../Responsive";

export default StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#F4F6F8",
		padding: RFValue(15),
	},
	title: {
		fontSize: RFValue(26),
		fontWeight: "bold",
		color: "#333",
		textAlign: "center",
		marginBottom: RFValue(20),
	},
	sectionCard: {
		backgroundColor: "#fff",
		borderRadius: 12,
		padding: RFValue(15),
		marginBottom: RFValue(15),
		shadowColor: "#000",
		shadowOpacity: 0.05,
		shadowOffset: { width: 0, height: 2 },
		shadowRadius: 5,
		elevation: 2,
	},
	buttonContainer: {
		flexDirection: "row",
		justifyContent: "space-between",
	},
	button: {
		flex: 1,
		alignItems: "center",
		padding: RFValue(12),
		marginHorizontal: RFValue(8),
		backgroundColor: "#4A90E2",
		borderRadius: 8,
		shadowColor: "#000",
		shadowOpacity: 0.1,
		shadowOffset: { width: 0, height: 2 },
		shadowRadius: 3,
		elevation: 2,
	},
	buttonText: {
		color: "#fff",
		fontWeight: "600",
		fontSize: RFValue(15),
	},
	input: {
		borderWidth: 1,
		borderColor: "#ddd",
		borderRadius: 8,
		padding: RFValue(12),
		height: RFValue(200),
		textAlignVertical: "top",
		backgroundColor: "#FAFAFA",
		fontSize: RFValue(16),
	},
	charCount: {
		marginTop: RFValue(8),
		textAlign: "right",
		fontSize: RFValue(13),
	},
	actionContainer: {
		flexDirection: "row",
		flexWrap: "wrap",
		justifyContent: "space-between",
	},
	actionButton: {
		alignItems: "center",
		paddingVertical: RFValue(10),
		paddingHorizontal: RFValue(15),
		margin: RFValue(5),
		backgroundColor: "#2ECC71",
		borderRadius: 8,
		elevation: 1,
		minWidth: RFValue(90),
	},
	actionButtonText: {
		fontSize: RFValue(14),
		color: "#fff",
		fontWeight: "600",
	},
	checkboxRow: {
		flexDirection: "row",
		alignItems: "center",
	},
	checkboxText: {
		marginLeft: RFValue(8),
		fontSize: RFValue(14),
		color: "#555",
	},
	footer: {
		alignItems: "center",
		marginTop: RFValue(15),
	},
	helpText: {
		fontSize: RFValue(16),
		fontWeight: "bold",
		marginBottom: RFValue(10),
	},
	coffeeButton: {
		backgroundColor: "#F7B500",
		paddingHorizontal: RFValue(15),
		paddingVertical: RFValue(8),
		borderRadius: 8,
	},
	coffeeButtonText: {
		color: "#fff",
		fontWeight: "bold",
		fontSize: RFValue(14),
	},
	languageContainer: {
		alignSelf: "flex-end",
		marginBottom: RFValue(15),
		marginTop: RFValue(10),
	},
	languageButton: {
		backgroundColor: "#E74C3C",
		paddingVertical: RFValue(8),
		paddingHorizontal: RFValue(12),
		borderRadius: 8,
	},
	languageButtonText: {
		fontSize: RFValue(14),
		color: "#fff",
		fontWeight: "600",
	},
});
